---
abstract: 'Yet another mail sender'
author:
  - 'Tokuhiro Matsuno E<lt>tokuhirom AAJKLFJEF@ GMAIL COME<gt>'
build_requires:
  Test::More: 0.98
  Test::Requires: 0
configure_requires:
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Module::Build version 0.4003, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mail-Krohn
no_index:
  directory:
    - inc
provides:
  Mail::Krohn:
    file: lib/Mail/Krohn.pm
    version: 0.01
  Mail::Krohn::Base:
    file: lib/Mail/Krohn/Base.pm
    version: 0
  Mail::Krohn::Sendmail:
    file: lib/Mail/Krohn/Sendmail.pm
    version: 0
  Mail::Krohn::Test:
    file: lib/Mail/Krohn/Test.pm
    version: 0
requires:
  Class::Accessor::Lite: 0.05
  Email::MIME: 0
  Exporter: 0
  parent: 0
  perl: 5.008005
resources:
  license: http://dev.perl.org/licenses/
version: 0.01
